export default {
  'back-extensors': require('./icons8-back-extensors-filled-50.png'),
  'barbell-push': require('./barbell-push.png'),
  'bench-press': require('./icons8-bench-press-50.png'),
  'body-builder': require('./icons8-bodybuilder-filled-50.png'),
  calves: require('./icons8-calves-50.png'),
  chest: require('./icons8-chest-filled-50.png'),
  crunches: require('./crunches.png'),
  'curl-bar': require('./icons8-ez-curl-bar-50.png'),
  curls: require('./curls.png'),
  deadlift: require('./deadlift.png'),
  'incline-push': require('./incline-push.png'),
  leg: require('./leg.png'),
  'military-press': require('./incline-push.png'),
  muscle: require('./icons8-muscle-50.png'),
  prelum: require('./icons8-prelum-filled-50.png'),
  pullups: require('./pullups.png'),
  quadriceps: require('./icons8-quadriceps-filled-50.png'),
  row: require('./row.png'),
  'rowing-machine': require('./icons8-rowing-machine-50.png'),
  shoulders: require('./icons8-shoulders-filled-50.png'),
  squat: require('./squats.png'),
  triceps: require('./icons8-triceps-50.png'),
  warmup: require('./icons8-warm-up-50.png'),
};
