/** The real route modules, mounted in expo-router's in-memory test router. */
export const routes = () => ({
  _layout: require('../app/_layout'),
  '(tabs)/_layout': require('../app/(tabs)/_layout'),
  '(tabs)/index': require('../app/(tabs)/index'),
  '(tabs)/progress': require('../app/(tabs)/progress'),
  '(tabs)/plan': require('../app/(tabs)/plan'),
  '(tabs)/settings': require('../app/(tabs)/settings'),
  history: require('../app/history'),
  'plan/rules': require('../app/plan/rules'),
  'setup/_layout': require('../app/setup/_layout'),
  'setup/index': require('../app/setup/index'),
  'setup/gym': require('../app/setup/gym'),
  'setup/plan': require('../app/setup/plan'),
  'setup/review': require('../app/setup/review'),
  'setup/days': require('../app/setup/days'),
  'setup/confirm': require('../app/setup/confirm'),
  'exercises/index': require('../app/exercises/index'),
  'exercises/[id]': require('../app/exercises/[id]'),
  'lift/[id]': require('../app/lift/[id]'),
  'session/[n]': require('../app/session/[n]'),
  'session/edit/[n]': require('../app/session/edit/[n]'),
});
